export const dietOptions = {
    'Balanceada': 'balanced',
    'Alta en fibra': 'high-fiber',
    'Alta en proteína': 'high-protein',
    'Baja en carbohidratos': 'low-carb',
    'Baja en grasa': 'low-fat',
    'Baja en sodio': 'low-sodium',
  };
  
  export const healthOptions = {
    'Sin alcohol': 'alcohol-free',
    'Sin crustáceos': 'crustacean-free',
    'Sin lácteos': 'dairy-free',
    'Sin huevo': 'egg-free',
    'Sin pescado': 'fish-free',
    'Bajo en FODMAP': 'fodmap-free',
    'Sin gluten': 'gluten-free',
    'Soporte inmunitario': 'immuno-supportive',
    'Cetogenico': 'keto-friendly',
    'Amigable con los riñones': 'kidney-friendly',
    'Kosher': 'kosher',
    'Bajo en grasas saturadas': 'low-fat-abs',
    'Bajo en potasio': 'low-potassium',
    'Bajo en azúcar': 'low-sugar',
    'Libre de lupino': 'lupine-free',
    'Mediterráneo': 'Mediterranean',
    'Sin moluscos': 'mollusk-free',
    'Sin mostaza': 'mustard-free',
    'Sin aceite añadido': 'no-oil-added',
    'Paleo': 'paleo',
    'Sin maní': 'peanut-free',
    'Pescatariano': 'pescatarian',
    'Sin cerdo': 'pork-free',
    'Sin carne roja': 'red-meat-free',
    'Sin sésamo': 'sesame-free',
    'Sin mariscos': 'shellfish-free',
    'Sin soya': 'soy-free',
    'Consciente del azúcar': 'sugar-conscious',
    'Sin sulfitos': 'sulfite-free',
    'Libre de frutos secos': 'tree-nut-free',
    'Vegano': 'vegan',
    'Vegetariano': 'vegetarian',
    'Sin trigo': 'wheat-free',
  };